/* Generated By:JavaCC: Do not edit this line. LanguageParserConstants.java */
package classes;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LanguageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA = 14;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL = 15;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO = 16;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL = 17;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 18;
  /** RegularExpression Id. */
  int DIGITO = 19;
  /** RegularExpression Id. */
  int NUMERO_DECIMAL = 20;
  /** RegularExpression Id. */
  int CONSTANTE_INTEIRO = 21;
  /** RegularExpression Id. */
  int CONSTANTE_REAL = 22;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL = 23;
  /** RegularExpression Id. */
  int LETRA = 24;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 25;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 26;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 27;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 28;
  /** RegularExpression Id. */
  int CONSTANTE_INTEIRA_INVALIDA = 29;
  /** RegularExpression Id. */
  int CONSTANTE_REAL_INVALIDA = 30;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL_INVALIDA = 31;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIO_LINHA = 1;
  /** Lexical state. */
  int COMENTARIO_BLOCO = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\r\\n\"",
    "\"\\n\\r\"",
    "\"//\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 13>",
    "<PALAVRA_RESERVADA>",
    "<SIMBOLO_ESPECIAL>",
    "<OPERADOR_ARITMETICO>",
    "<OPERADOR_RELACIONAL>",
    "<OPERADOR_LOGICO>",
    "<DIGITO>",
    "<NUMERO_DECIMAL>",
    "<CONSTANTE_INTEIRO>",
    "<CONSTANTE_REAL>",
    "<CONSTANTE_LITERAL>",
    "<LETRA>",
    "<LETRA_MAIUSCULA>",
    "<LETRA_MINUSCULA>",
    "<IDENTIFICADOR>",
    "<SIMBOLO_INVALIDO>",
    "<CONSTANTE_INTEIRA_INVALIDA>",
    "<CONSTANTE_REAL_INVALIDA>",
    "<CONSTANTE_LITERAL_INVALIDA>",
    "<IDENTIFICADOR_INVALIDO>",
  };

}
